name: roadvert_beacon
description: Roadvert WebView wrapper with NFC & Eddystone support
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.4.0
  flutter_nfc_kit: ^3.6.0
  webview_flutter: ^4.10.0
  url_launcher: ^6.1.7
  permission_handler: ^12.0.0+1
  http: ^1.4.0
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo-roadvert.png
    
